[2022-12-28T17:39:05.679-0300] {processor.py:153} INFO - Started process (PID=13708) to work on /home/debian/Documentos/PYTHONJOBS/airflowapp/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-28T17:39:05.679-0300] {processor.py:743} INFO - Processing file /home/debian/Documentos/PYTHONJOBS/airflowapp/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-28T17:39:05.680-0300] {logging_mixin.py:137} INFO - [2022-12-28T17:39:05.680-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/debian/Documentos/PYTHONJOBS/airflowapp/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-28T17:39:05.692-0300] {logging_mixin.py:137} INFO - [2022-12-28T17:39:05.692-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/Documentos/PYTHONJOBS/airflowapp/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-28T17:39:05.692-0300] {logging_mixin.py:137} INFO - [2022-12-28T17:39:05.692-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-28T17:39:05.693-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/debian/Documentos/PYTHONJOBS/airflowapp/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-28T17:39:05.700-0300] {processor.py:175} INFO - Processing /home/debian/Documentos/PYTHONJOBS/airflowapp/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
